# Generated by Django 4.0.4 on 2023-06-29 18:38

import api.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLogModel',
            fields=[
                ('sys_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, max_length=1024)),
                ('path', models.CharField(blank=True, max_length=1024)),
                ('method', models.CharField(blank=True, max_length=8)),
                ('data', models.TextField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('referrer', models.CharField(blank=True, max_length=512, null=True)),
                ('timestamp', models.DateTimeField(blank=True)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendant',
            fields=[
                ('atdt_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('employee_id', models.CharField(max_length=200)),
                ('location_id', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=400)),
                ('vouchers', models.IntegerField()),
                ('profile', models.ImageField(blank=True, null=True, upload_to=api.models.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='chat',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=400)),
                ('employee_id', models.CharField(max_length=200)),
                ('status', models.CharField(default='U', max_length=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 6, 29, 18, 38, 15, 528787, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='ClientMaster',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=200)),
                ('address', models.CharField(default='c_addr', max_length=400)),
                ('contact_name', models.CharField(default='c_name', max_length=400)),
                ('contact_no', models.CharField(default='c_no', max_length=400)),
                ('active_vouchers', models.IntegerField(default=0)),
                ('used_vouchers', models.IntegerField(default=0)),
                ('last_order_date', models.DateField(blank=True, default=None, null=True)),
                ('last_order_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('voucher_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('initial_amount', models.BigIntegerField()),
                ('balance', models.BigIntegerField()),
                ('last_used', models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 29, 18, 38, 15, 527787, tzinfo=utc), null=True)),
                ('last_transaction_id', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('status', models.CharField(default='A', max_length=1)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clientmaster')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('txn_date', models.DateTimeField(default=datetime.datetime(2023, 6, 29, 18, 38, 15, 528787, tzinfo=utc))),
                ('txn_id', models.AutoField(primary_key=True, serialize=False)),
                ('initial_amount', models.BigIntegerField(null=True)),
                ('redeem_amount', models.BigIntegerField(null=True)),
                ('left_balance', models.BigIntegerField(null=True)),
                ('Voucher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.voucher')),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.attendant')),
            ],
        ),
    ]
