# Generated by Django 4.2.2 on 2023-07-06 11:15

import api.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLogModel',
            fields=[
                ('sys_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, max_length=1024)),
                ('path', models.CharField(blank=True, max_length=1024)),
                ('method', models.CharField(blank=True, max_length=8)),
                ('data', models.TextField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('referrer', models.CharField(blank=True, max_length=512, null=True)),
                ('timestamp', models.DateTimeField(blank=True)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendant',
            fields=[
                ('atdt_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('date_of_borth', models.DateField(blank=True, null=True)),
                ('employee_id', models.CharField(max_length=200)),
                ('location_id', models.CharField(blank=True, max_length=200, null=True)),
                ('password', models.CharField(max_length=400)),
                ('vouchers', models.IntegerField(blank=True, default=0)),
                ('profile', models.ImageField(blank=True, null=True, upload_to=api.models.user_directory_path)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(default='NA', max_length=100)),
                ('created_time', models.DateTimeField(default=datetime.datetime(2023, 7, 6, 11, 15, 33, 553622, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='chat',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=400)),
                ('employee_id', models.CharField(max_length=200)),
                ('status', models.CharField(default='U', max_length=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 7, 6, 11, 15, 33, 554622, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='ClientMaster',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=200)),
                ('address', models.CharField(default='c_addr', max_length=400)),
                ('contact_name', models.CharField(default='c_name', max_length=400)),
                ('contact_no', models.CharField(default='c_no', max_length=400)),
                ('active_vouchers', models.IntegerField(blank=True, default=0, null=True)),
                ('used_vouchers', models.IntegerField(blank=True, default=0, null=True)),
                ('last_order_date', models.DateField(blank=True, default=None, null=True)),
                ('last_order_amount', models.IntegerField(default=0)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_time', models.DateTimeField(default=datetime.datetime(2023, 7, 6, 11, 15, 33, 553622, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('station_name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(max_length=100)),
                ('operated_hours', models.CharField(max_length=100)),
                ('created_time', models.DateTimeField(default=datetime.datetime(2023, 7, 6, 11, 15, 33, 551157, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('department', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('created_time', models.DateTimeField(default=datetime.datetime(2023, 7, 6, 11, 15, 33, 555897, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('voucher_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('initial_amount', models.BigIntegerField()),
                ('balance', models.BigIntegerField()),
                ('last_used', models.DateField(blank=True, default=None, null=True)),
                ('last_transaction_id', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('status', models.CharField(default='A', max_length=1)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_time', models.DateTimeField(default=datetime.datetime(2023, 7, 6, 11, 15, 33, 554622, tzinfo=datetime.timezone.utc))),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clientmaster')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('txn_date', models.DateTimeField(default=datetime.datetime(2023, 7, 6, 11, 15, 33, 554622, tzinfo=datetime.timezone.utc))),
                ('txn_id', models.AutoField(primary_key=True, serialize=False)),
                ('initial_amount', models.BigIntegerField(null=True)),
                ('redeem_amount', models.BigIntegerField(null=True)),
                ('left_balance', models.BigIntegerField(null=True)),
                ('Voucher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.voucher')),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.attendant')),
            ],
        ),
        migrations.AddField(
            model_name='attendant',
            name='station_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.station'),
        ),
    ]
