# Generated by Django 4.2.2 on 2023-07-06 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendant',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 11, 16, 38, 590591, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 11, 16, 38, 593589, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='clientmaster',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 11, 16, 38, 591586, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='station',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 11, 16, 38, 590591, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='txn_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 11, 16, 38, 592586, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='users',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 11, 16, 38, 593589, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 11, 16, 38, 592586, tzinfo=datetime.timezone.utc)),
        ),
    ]
