# Generated by Django 4.2.2 on 2023-07-06 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_attendant_created_time_alter_chat_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendant',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 14, 48, 29, 368986, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 14, 48, 29, 369984, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='clientmaster',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 14, 48, 29, 368986, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='station',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 14, 48, 29, 366985, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='txn_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 14, 48, 29, 369984, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='users',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 14, 48, 29, 370983, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 14, 48, 29, 369984, tzinfo=datetime.timezone.utc)),
        ),
    ]
