# Generated by Django 4.2.2 on 2023-07-02 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_users_attendant_created_by_attendant_modified_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendant',
            name='location_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='attendant',
            name='vouchers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 2, 15, 1, 20, 577888, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='txn_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 2, 15, 1, 20, 577888, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='last_used',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 2, 15, 1, 20, 576885, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
