# Generated by Django 4.2.2 on 2023-07-02 19:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_attendant_location_id_alter_attendant_vouchers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('station_name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(max_length=100)),
                ('operated_hours', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='attendant',
            name='date_of_borth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendant',
            name='department',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='attendant',
            name='vouchers',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 2, 19, 4, 47, 448911, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='txn_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 2, 19, 4, 47, 446683, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='last_used',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 2, 19, 4, 47, 444982, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AddField(
            model_name='attendant',
            name='station_id',
            field=models.ForeignKey(default='999', on_delete=django.db.models.deletion.DO_NOTHING, to='api.station'),
        ),
    ]
