# Generated by Django 4.2.2 on 2023-07-02 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_station_attendant_date_of_borth_attendant_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendant',
            name='station_id',
        ),
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 2, 19, 11, 47, 565325, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='txn_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 2, 19, 11, 47, 564325, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='last_used',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 2, 19, 11, 47, 564325, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
