# Generated by Django 4.2.2 on 2023-07-06 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_attendant_created_time_alter_chat_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendant',
            old_name='date_of_borth',
            new_name='date_of_birth',
        ),
    ]
