# Generated by Django 4.2.2 on 2023-07-02 19:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_attendant_station_id_alter_chat_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendant',
            name='station_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.station'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 2, 19, 18, 33, 847023, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='txn_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 2, 19, 18, 33, 846002, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='last_used',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 2, 19, 18, 33, 846002, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
