# Generated by Django 4.2.2 on 2023-07-06 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_station_id_attendant_staton_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendant',
            old_name='staton_id',
            new_name='station_id',
        ),
    ]
