# Generated by Django 4.2.2 on 2023-07-03 10:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_chat_created_at_alter_transactions_txn_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('station_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('station_name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(max_length=100)),
                ('operated_hours', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 3, 10, 9, 48, 27769, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='txn_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 3, 10, 9, 48, 26685, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='attendant',
            name='station_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.stations'),
        ),
        migrations.DeleteModel(
            name='Station',
        ),
    ]
