# Generated by Django 4.2.2 on 2023-07-03 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_stations_alter_chat_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 3, 12, 36, 55, 816257, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='txn_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 3, 12, 36, 55, 816257, tzinfo=datetime.timezone.utc)),
        ),
    ]
