# Generated by Django 4.2.2 on 2023-07-03 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_chat_created_at_alter_transactions_txn_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 3, 12, 44, 22, 657954, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='txn_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 3, 12, 44, 22, 656876, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='last_used',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
