# Generated by Django 4.2.2 on 2023-07-03 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_chat_created_at_alter_transactions_txn_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stations',
            new_name='Station',
        ),
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 3, 12, 49, 15, 540045, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='txn_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 3, 12, 49, 15, 539046, tzinfo=datetime.timezone.utc)),
        ),
    ]
